Update readme
matchms/ms2deepscore pull request #82
Opened 2021-03-25 16:21 UTC by svenvanderburg

* Update README with a bit more introduction to the project, a quick start section, and a bit on contributing
* Add tutorial notebook that is a more extensive working example of the quick start section
* Add CONTRIBUTING.md

2021-03-25 16:29 UTC, florian-huber commented on README.md
> +###Prepare environment
```suggestion
### Prepare environment
```

2021-03-25 16:30 UTC, florian-huber commented on README.md
> +We welcome contributions to the development of ms2deepscore! Have a look at the [contribution guidelines](ttps://github.com/matchms/ms2deepscore/blob/main/CONTRIBUTING.md).
```suggestion
We welcome contributions to the development of ms2deepscore! Have a look at the [contribution guidelines](https://github.com/matchms/ms2deepscore/blob/main/CONTRIBUTING.md).
```

2021-03-25 16:32 UTC, florian-huber commented on CONTRIBUTING.md
> +1. use the search functionality [here](https://github.com/iomega/spec2vec/issues) to see if someone already filed the same issue;
```suggestion
1. use the search functionality [here](https://github.com/matchms/ms2deepscore/issues) to see if someone already filed the same issue;
```

2021-03-25 16:32 UTC, florian-huber commented on CONTRIBUTING.md
> +1. [push](http://rogerdudler.github.io/git-guide/>) your feature branch to (your fork of) the spec2vec repository on GitHub;
```suggestion
1. [push](http://rogerdudler.github.io/git-guide/>) your feature branch to (your fork of) the ms2deepscore repository on GitHub;
```

2021-03-25 16:32 UTC, florian-huber commented on CONTRIBUTING.md
> +1. Goto [GitHub release page](https://github.com/iomega/spec2vec/releases)
```suggestion
1. Goto [GitHub release page](https://github.com/matchms/ms2deepscore/releases)
```

2021-03-25 16:34 UTC, florian-huber commented on CONTRIBUTING.md
> +A GitHub action will run which will publish the new version to [anaconda](https://anaconda.org/nlesc/spec2vec).
```suggestion
A GitHub action will run which will publish the new version to [pypi](https://pypi.org/project/ms2deepscore).
```

2021-03-25 16:34 UTC, florian-huber commented on CONTRIBUTING.md
> +Also a Zenodo entry will be made for the release with its own DOI.
This is not implemented yet I believe. Could become a new issue

2021-03-25 16:35 UTC, florian-huber requested changes
Thanks a lot for adding this Sven!
I added some small corrections, but otherwise looks great!

2021-03-31 13:28 UTC, svenvanderburg commented
Nice catches! (I will pay a bit more attention when I copy-paste next time :) )

2021-03-31 13:28 UTC, merged